config/routes.rb
Rails.application.routes.draw do

  # routes to home controller
  root to: 'home', to: 'home#menu', as: "home-menu"

  # routes to static controller
  get 'about', to: 'static#about', as: "about"
  get 'instructions', to: 'static#instructions', as: "instructions"
  get 'ingredients-list', to: 'static#ingredients_list', as: 'ingredients_list'

  #routes to play controller

  get '/play/choose-chef', to: 'play#choose_chef', as: "chef_selection_form"
  post '/play/choose-chef', to: 'play#chef_selected', as: "chef_selected"

  get 'play/edit-chef', to: 'play#edit_chef', as: "chef_edit_form"
  post 'play/edit-chef', to: 'play#chef_editted', as: "chef_editted"

  get 'play/create-chef', to: 'play#create_chef', as: "chef_create_form"
  post 'play/create-chef', to: 'play#chef_created', as: "chef_created"

  get 'play/delete-chef', to: 'play#delete_chef', as: "chef_delete_form"
  post 'play/delete-chef', to: 'play#chef_deleted', as: "chef_deleted"

  get '/play/pick-ingredients', to: 'play#pick_ingredients', as: "ingredients_pick_form"
  post '/play/pick-ingredients', to: 'play#ingredients_picked', as: "ingredients_picked"

  get '/play/result', to: 'play#result', as: "result"

  get '/play/lose', to: 'play#lose', as: "lose"

  get '/play/win', to: 'play#win', as: "win"

end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :recipe_ingredients # a recipe has many recipe_ignredients (association)
    has_many :ingredients, through: :recipe_ingredients # a recipe has many ingredients through its associations

    GARBAGE = Recipe.find_by(name: "Garbage") # constant for the garbage recipe

    # this method checks if a given list of ingredients names exists in any recipe
    def self.ingredient_list_exists?(ingredient_names_array)
            Recipe.all.any? do |recipe| # if any recipe meets my condition
                ingredients_on_this_recipe = recipe.get_ingredients_names # get the ignredients names from the recipe
                
                ingredient_names_array.sort == ingredients_on_this_recipe.sort # CONDITION: do the ingredients given match the ingredients on the recipe                 
            end
    end

    # this method returns a recipe of garbage if the ignredients names matches a recipe's ingredients names
    def self.recipe_or_garbage(ingredients_names_array)
        if ingredients_names_array.size > 0 || ingredients_names_array != nil # checking the argument to see if its not empty or null
            recipeResult = Recipe.all.detect {|recipe| # detect the first recipe that meets my condition
            recipe.get_ingredients_names.sort == ingredients_names_array.sort} # CONDITION: if the recipe's ignredients names match the argument's ingredients' names
            
            if recipeResult == nil # if our detect hasn't found anything
                return GARBAGE # the result should be garbage
            else    # if our detect found a recipe
                return recipeResult # the result should be the recipe we found
            end
        else # if the argument is empty or nil
            return GARBAGE # return garbage
        end

    end

    # this method creates a recipe by giving it some ingredients names (used for seeding)
    def self.create_by_ingredient_names(recipeName, recipeDamage , ingredient_names_array)
        if ingredient_list_exists?(ingredient_names_array) == false # if we haven't given this list before
            thisRecipe = Recipe.create(name: recipeName, damage: recipeDamage) # create a new recipe of the desired name and damage
            ingredient_names_array.each do |ingredient_name| # for every ingredient name given
                ingredientToAdd = Ingredient.find_or_create_by(name: ingredient_name) # find or create the ingredient by name
                RecipeIngredient.create(recipe_id: thisRecipe.id, ingredient_id: ingredientToAdd.id) # create an association between the recipe and ingredient
            end

            return thisRecipe # return the recipe
        else # if the list has been given before
            puts "Ingredients List for #{recipeName} Is Not Unique!" # print out a helpful message telling me the list isn't unique
        end      
    end

    # this method prints out the ingredients names of the recipe's ingredients
    def get_ingredients_names
        self.ingredients.map{|ingredient| ingredient.name}
    end

    # this method actually outputs the ingredients names of the recipe (for use in a view file)
    def present_ingredients_names
        get_ingredients_names.reduce("") {|memo, name| memo + ", #{name}"}.delete_prefix(", ")
    end
end

app/controllers/play_controller.rb
class PlayController < ApplicationController
    skip_before_action :verify_authenticity_token

    def choose_chef #prefix: chef_selection_form
        @available_chefs = Chef.all # create chef collection for view
        @chef = Chef.new # create chef instance for form_for
    end

    def chef_selected #prefix: chef_selected
        Chef.reset_all_health # reset all chef's lives
        Monster.all.reset_all_health # reset all monster health
        session[:chef_id] = params[:chef][:id] # REMEMBER the chef that was selected in the form
        session[:monster_id] = Monster.select_random_living_monster.id # REMEMBER a random living monster
        redirect_to ingredients_pick_form_path # redirect to the ingredient pick form - action
    end

    def create_chef #prefix: chef_create_form
        @chef_images = Chef.chef_image_names # get all the chef images and save them to use in view (image-tags)
        @chef = Chef.new # create chef instance for form_for
    end

    def chef_created #prefix: chef_created
        if params[:chef][:name] == nil || params[:chef][:name] == "" || params[:chef][:image_name] == nil
            @chef = Chef.new # create chef instance for form_for
            @chef_images = Chef.chef_image_names # get all the chef images and save them to use in view (image-tags)
            @error_message = flash[:error_message] = "Invalid Inputs"
            render 'create_chef'
        else
            Chef.setup_new_chef(params[:chef][:name], params[:chef][:image_name], params[:chef][:image_name].ext('gif')) # create a new chef based on input
            redirect_to chef_selection_form_path # redirect to chef selection page
        end

    end

    def edit_chef #prefix: chef_edit_form
        @chef = Chef.new # create chef instance for form_for
        @chef_images = Chef.chef_image_names # get all the chef images and save them to use in view (image-tags)
    end

    def chef_editted #prefix: chef_editted
        if params[:chef][:name] == nil || params[:chef][:name] == "" || params[:chef][:image_name] == nil
            @chef = Chef.new # create chef instance for form_for
            @chef_images = Chef.chef_image_names # get all the chef images and save them to use in view (image-tags)
            @error_message = flash[:error_message] = "Invalid Inputs"
            render 'edit_chef'
        else
            Chef.find(params[:chef][:id]).update(name: params[:chef][:name], image_name: params[:chef][:name], gif_name: params[:chef][:image_name].ext('gif')) # update the chef selected in form
            redirect_to chef_selection_form_path # redirect to chef selection page
        end
    end

    def delete_chef #prefix: chef_delete_form
        @chef = Chef.new # create a new chef for a form_for
    end

    def chef_deleted #prefix: chef_deleted
        Chef.destroy(params[:chef][:id]) # delete chef based on id passed back from deletion form
        redirect_to chef_selection_form_path # redirect to chef selection page
    end

    def pick_ingredients #prefix: ingredients_pick_form
        puzzleHash = Ingredient.create_ingredients_puzzle(8) # generate a puzzle Hash with 8 ingredients
        session[:recipe_answer_id] = puzzleHash[:recipe_answer_id] # REMEMBER but the "correct" recipe answer is
        @ingredients = puzzleHash[:ingredients_given].shuffle # get the ingredients list from the puzzle hash and randomize it
        @current_monster = Monster.find(session[:monster_id]) # get the current monster from the session to use in the view
        @current_chef = Chef.find(session[:chef_id]) # get the current chef from the session to use in the view
    end

    def ingredients_picked #prefix: ingredients_picked
            if params[:ingredient_ids] == nil # if the user has not selected any ingredients in the selection page
                @recipe_made = Recipe.find_by(name: "Garbage")  # set the recipe made to Garbage
            else    # if th user HAS selected ingredients
                @ingredients_selected = params[:ingredient_ids].map{|id| Ingredient.find(id).name} # turn the passed ingredient id's into their respective names
                @recipe_made = Recipe.recipe_or_garbage(@ingredients_selected) # check if the selected recipes make garbage or not
            end

            @monster = Monster.find(session[:monster_id]) # set the monster to the session's monster for the view
            @chef = Chef.find(session[:chef_id]) # set the chef for the session's chef for the view
            session[:recipe_id] = @recipe_made.id # REMEMBER the recipe id that the user created
           
        if @recipe_made.name == "Garbage" # if the recipe the user made was Garbage
            if @chef.lives - 1 == 0 # if the chef has no more lives left
                redirect_to lose_path # redirect to the lose page
            else # else if the chef still has lives to lose
                @chef.update(lives: @chef.lives - 1) # reduce the chef's lives by 1
                redirect_to result_path # redirect to the result page
            end
        else # else if the user made an actual recipe
            if @monster.health - @recipe_made.damage <= 0 # if the monster is about to take "fatal" damage
                @monster.update(health: @monster.health - @recipe_made.damage) # reduce the monster's health (so it is recognized as defeated)
                redirect_to win_path # redirect to the win page
            else # else if the monster is still going to live after taking damage
                @monster.update(health: @monster.health - @recipe_made.damage) # reduce the monster's health
                redirect_to result_path # redirect to the result page
            end
        end
    end

    def result #prefix: result
        @correct_answer = Recipe.find(session[:recipe_answer_id]) # get the correct answer from the session for the view
        @recipe_made = Recipe.find(session[:recipe_id]) # get the recipe the user made from the session for the view
        @current_monster = Monster.find(session[:monster_id]) # get the current monster from the session for the view
        @current_chef = Chef.find(session[:chef_id]) # get the current chef from the session for the view
    end

    def lose #prefix: lose
        @recipe_made = Recipe.find(session[:recipe_id]) # get the recipe made from the session for the view
        @current_chef = Chef.find(session[:chef_id]) # get the current chef from the session for the view
        @current_monster = Monster.find(session[:monster_id]) # get the current monster from the session for the view
    end

    def win #prefix: win
        @recipe_made = Recipe.find(session[:recipe_id]) # get the recipe made from the session for the view
        @won_game = Monster.all_defeated? # check if the user has defeated all the monsters
        @current_chef = Chef.find(session[:chef_id]) # get the current chef from the session for the view
        @current_monster = Monster.find(session[:monster_id]) # get the current monster from the session for the view
        if @won_game == false # if the game has not been won
            @next_monster = Monster.select_random_living_monster # get another living monster and set them as the next monster for the view
            session[:monster_id] = @next_monster.id # REMEMBER who the next monster is 
        end
    end
end

app/views/play/choose_chef.erb
<div class="page_title">
    <h1> CHEF SELECTION <h2>
</div>
<% if @available_chefs.size >= 1 %>
<div class="container_page_options">
    <%= form_for(@chef, url: {action: "chef_selected"}, method: :post) do |f| %>
        <%= f.collection_select :id, @available_chefs, :id, :name %>
        <%= f.submit "Begin Game!" %>
    <% end %>
</div>
<br>

<div class="container_page_options">   
<%= button_to "Edit Your Chef", chef_edit_form_path, method: :get %>
<%= button_to "Delete A Chef", chef_delete_form_path, method: :get %>

</div>
<% end %>
<div class="container_page_options"> 
    <%= button_to "Add Chef", chef_create_form_path, method: :get %>
</div>

app/views/play/create_chef.erb
<div class="page_title">
    <h1> CREATE YOUR CHEF <h2>
</div>

<div class = "error_container">
    <% if @error_message != nil %>
        <div class="error_message">
            <%= @error_message %>
        </div>
        <br><br>
    <% end %>
</div>

<%= form_for(@chef, url: {action: 'chef_created'}, method: :post) do |f| %>
    
    <div class = "page_title">
    <h3> Pick Your Appearance! </h3>
    </div>

    <div class='container_chef_image_selection'>
        <% @chef_images.each do |img_name| %>
                <%= image_tag(img_name)%>
                <%= radio_button("chef", "image_name", img_name) %>  
                <br>
        <% end %>
    </div>
    <br>
    
    <div class="container_page_options">
        <%= f.label :name %>
        <%= f.text_field :name %>
        <br>
        <%= f.submit "Create Chef"%>
    </div>
<% end %>

app/views/play/delete_chef.erb
<div class="page_title">
    <h1> DELETE YOUR CHEF <h2>
</div>

<div class="container_page_options">
    <%= form_for(@chef, url: {action: 'chef_deleted'}, method: :post) do |f| %>
        <%= f.collection_select :id, Chef.all, :id, :name%>
        <%= f.submit "Delete Chef" %>
        <br>
    <% end %>
</div>

app/views/play/edit_chef.erb
<div class="page_title">
    <h1> EDIT A CHEF <h2>
</div>

<div class = "error_container">
    <% if @error_message != nil %>
        <div class="error_message">
            <%= @error_message %>
        </div>
        <br><br>
    <% end %>
</div>

    <%= form_for(@chef, url: {action: "chef_editted"}, method: :post) do |f| %>
        <div class='container_chef_image_selection'>
            <% @chef_images.each do |img_name| %>
                <%= image_tag(img_name)%>
                <%= radio_button("chef", "image_name", img_name) %>
                <br>
            <% end %>
        </div>
        <br>
        
        <div class="container_page_options">
            <%= f.collection_select :id, Chef.all, :id, :name %>
            <%= f.label :name %>
            <%= f.text_field :name %>
            <br>
            <%= f.submit "Edit Chef!" %>
        </div>
    <% end %>

app/views/play/lose.erb
<div class="page_title">
    <h1> OH NO! YOU MESSED UP FOR THE LAST TIME </h1>
</div>

 <%= audio_tag "fail#{rand(1..12)}.mp3", autoplay: true %>

<div class="container_chef_monster_img">
<%= image_tag @current_chef.gif_name %>

<%= image_tag @current_monster.gif_name %>
</div>


<div class="page_content"><h3> YOUR FOOD TASTES REALLY, REALLY BAD! </h3></div>

<div class="page_content"><p> Oh No! Your reputation has been foiled! <%= @current_monster.name %> writes a seething Yelp review! </p></div>
<div class="page_content"><p> The Health Department will be coming to shut you down soon! Bummer! </p></div>
</div>

<div class="container_page_options">
    <%= button_to "Try Again!", chef_selection_form_path, method: 'get' %>
</div>

app/views/play/pick_ingredients.erb
<div class="page_title">
    <h1> Make a Recipe! </h1>
</div>

<div class="container_chef_monster_img">
    <div class="img_caption">
        <%= image_tag @current_chef.gif_name%>
        Chef: <%= @current_chef.name %>
    </div>

    <div class="img_caption">
        <%= image_tag @current_monster.gif_name%>
        Customer: <%= @current_monster.name %>
    </div>
</div>

<div class="page_title">
    <h2> PICK YOUR INGREDIENTS! </h2>
</div>

<%= form_with url: ingredients_picked_path do |form| %>
    <div class="container_ingredient_selection">
    <% @ingredients.each do |ingredient| %>  
        <div class="container_ingredient_option">
            <%= check_box_tag 'ingredient_ids[]', ingredient.id %>
            <%= image_tag(ingredient.image_name)%><br>
            <%= ingredient.name %>
        </div>
        <br>
    <% end %>    
    </div>
    <br>

    <div class="container_page_options">
        <%= form.submit "Feed The Monster!" %>
    </div>
    <br>
<% end %>

<div class="container_page_options">
<%= button_to "Review Ingredients List", ingredients_list_path, method: 'get' %>
</div>

app/views/play/result.erb
<div class="page_title">
    <h1> You Use Some Ingredients Together! </h1>
</div>

<div class="container_chef_monster_img">
<%= image_tag @current_chef.gif_name%>

<%= image_tag @current_monster.gif_name%>
</div>

<div class="page_content">
<p> You create some <%= @recipe_made.name %> for <%= @current_monster.name %>! </p>
</div>

<div class="page_content">
<%= image_tag @recipe_made.image_name %>
</div>

<% if @recipe_made.name == "Garbage" %>
    <%= audio_tag "fail#{rand(1..12)}.mp3", autoplay: true %>
    <div class="page_content"><p> Digusting! <%= @current_monster.name %> does not like it! You get a bad Yelp review! -1 reputation points!</p> </div>
    <div class="page_content"><p> You have <%= @current_chef.lives %> reputation points left </p></div>

    <div class="page_content"><p> Doh! The recipe you should have made was: <%= @correct_answer.name %>!</p></div>
    <div class="page_content"><p> The ingredients you should have used are:  <%= @correct_answer.present_ingredients_names %>. </p></div>
<% else %>
    <%= audio_tag "success#{rand(1..10)}.mp3", autoplay: true %>
    <div class="page_content"><p> Fantastic! <%= @current_monster.name %> eats it up for <%= @recipe_made.damage %> fullness points! </p></div>
    <div class="page_content"><p> <%= @current_monster.name %> has <%= @current_monster.health %> stomach points left! </p></div>
<% end %>
</div>

<div class = "container_page_options">
<%= button_to "Keep Going!", ingredients_pick_form_path, method: 'get' %>
</div>

app/views/play/transition.erb
<div class="page_title">
    <h1> IT'S TIME TO GET COOKING! </h1>
</div>

<%= button_to "Choose Your Chef", chef_selection_form_path, method: :get%>

app/views/play/win.erb
<div class="page_title">
    <h1> ONE MORE SATISFIED CUSTOMER! </h1>
</div>

<div class="container_chef_monster_img">
<%= image_tag @current_chef.gif_name %>

<%= image_tag @current_monster.gif_name %>
</div>

<div class="page_content">
<p> The <%= @recipe_made.name %> you make stuffs <%= @current_monster.name %>! </p>
</div>

<%= audio_tag "success#{rand(1..10)}.mp3", autoplay: true %>

    <% if @won_game %>

        <div class="page_content"><p> Wow! What a day! You don't have any more customers! Nice work <%= @current_chef.name %>! </p></div>
        <div class="page_content"><%= button_to "Play Again!", chef_selection_form_path, method: 'get' %></div>
    <% else %>
        <div class="page_content"><p> <%= @current_monster.name %> leaves the restaurant happy! </p></div>
        <div class="page_content"><p> Oh but wait! You've got another customer! <%= @next_monster.name %> is ready to eat! </p></div>
        <div class="page_content"><%= image_tag @next_monster.image_name %></div>
        <div class="page_content"><%= button_to "Play Again!", ingredients_pick_form_path, method: 'get' %></div>
    <% end %>
</div>